export const carDetails = {
  engineTypes: [
    { id: 1, name: "Бензиновий" },
    { id: 2, name: "Дизельний" },
    { id: 3, name: "Гібридний" },
    { id: 4, name: "Гібридний plug-in" },
    { id: 5, name: "Електричний" },
    { id: 6, name: "Водневий" },
    { id: 7, name: "Газовий" },
  ],
  engineVolumes: [
    { id: 2, name: "0.6 л" },
    { id: 3, name: "0.7 л" },
    { id: 4, name: "0.8 л" },
    { id: 5, name: "0.9 л" },
    { id: 6, name: "1.0 л" },
    { id: 7, name: "1.1 л" },
    { id: 8, name: "1.2 л" },
    { id: 9, name: "1.3 л" },
    { id: 10, name: "1.4 л" },
    { id: 11, name: "1.5 л" },
    { id: 12, name: "1.6 л" },
    { id: 13, name: "1.7 л" },
    { id: 14, name: "1.8 л" },
    { id: 15, name: "1.9 л" },
    { id: 16, name: "2.0 л" },
    { id: 17, name: "2.1 л" },
    { id: 18, name: "2.2 л" },
    { id: 19, name: "2.3 л" },
    { id: 20, name: "2.4 л" },
    { id: 21, name: "2.5 л" },
    { id: 22, name: "2.6 л" },
    { id: 23, name: "2.7 л" },
    { id: 24, name: "2.8 л" },
    { id: 25, name: "2.9 л" },
    { id: 26, name: "3.0 л" },
    { id: 27, name: "3.1 л" },
    { id: 28, name: "3.2 л" },
    { id: 29, name: "3.3 л" },
    { id: 30, name: "3.4 л" },
    { id: 31, name: "3.5 л" },
    { id: 32, name: "3.6 л" },
    { id: 33, name: "3.7 л" },
    { id: 34, name: "3.8 л" },
    { id: 35, name: "3.9 л" },
    { id: 36, name: "4.0 л" },
    { id: 37, name: "4.1 л" },
    { id: 38, name: "4.2 л" },
    { id: 39, name: "4.3 л" },
    { id: 40, name: "4.4 л" },
    { id: 41, name: "4.5 л" },
    { id: 42, name: "4.6 л" },
    { id: 43, name: "4.7 л" },
    { id: 44, name: "4.8 л" },
    { id: 45, name: "4.9 л" },
    { id: 46, name: "5.0 л" },
    { id: 47, name: "5.1 л" },
    { id: 48, name: "5.2 л" },
    { id: 49, name: "5.3 л" },
    { id: 50, name: "5.4 л" },
    { id: 51, name: "5.5 л" },
    { id: 52, name: "5.6 л" },
    { id: 53, name: "5.7 л" },
    { id: 54, name: "5.8 л" },
    { id: 55, name: "5.9 л" },
    { id: 56, name: "6.0 л" },
    { id: 57, name: "6.1 л" },
    { id: 58, name: "6.2 л" },
    { id: 59, name: "6.3 л" },
    { id: 60, name: "6.4 л" },
    { id: 61, name: "6.5 л" },
    { id: 62, name: "6.6 л" },
    { id: 63, name: "6.7 л" },
    { id: 64, name: "6.8 л" },
    { id: 65, name: "6.9 л" },
    { id: 66, name: "7.0 л" },
    { id: 67, name: "7.1 л" },
    { id: 68, name: "7.2 л" },
    { id: 69, name: "7.3 л" },
    { id: 70, name: "7.4 л" },
    { id: 71, name: "7.5 л" },
    { id: 72, name: "7.6 л" },
    { id: 73, name: "7.7 л" },
    { id: 74, name: "7.8 л" },
    { id: 75, name: "7.9 л" },
    { id: 76, name: "8.0 л" },
    { id: 77, name: "8.1 л" },
    { id: 78, name: "8.2 л" },
    { id: 79, name: "8.3 л" },
    { id: 80, name: "8.4 л" },
    { id: 81, name: "8.5 л" },
    { id: 82, name: "8.6 л" },
    { id: 83, name: "8.7 л" },
    { id: 84, name: "8.8 л" },
    { id: 85, name: "8.9 л" },
    { id: 86, name: "9.0 л" },
  ],
  transmissionOptions: [
    { id: 2, value: "Механическая" },
    { id: 3, value: "Автоматическая" },
    { id: 4, value: "Роботизированная" },
    { id: 5, value: "Вариатор" },
  ],

  wheelDriveOptions: [
    { id: 2, name: "Передний", value: "Front" },
    { id: 3, name: "Задний", value: "Rear" },
    { id: 4, name: "Полный", value: "Four" },
  ],

   colors: [
     { label: "Білий", id: 2 },
     { label: "Чорний", id: 3 },
     { label: "Металік", id: 4 },
     { label: "Синій", id: 5 },
     { label: "Сірий", id: 6 },
     { label: "Червоний", id: 7 },
     { label: "Бежевий", id: 8 },
     { label: "Зелений", id: 9 },
     { label: "Жовтий", id: 10 },
     { label: "Золотий", id: 11 },
     { label: "Інший колір", id: 12 }
   ]
};
